language: c
env:
 - CABALVER=1.22 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.1
 - CABALVER=1.22 GHCVER=head

matrix:
  allow_failures:
   - env: CABALVER=1.22 GHCVER=7.10.1
   - env: CABALVER=1.22 GHCVER=head
    
before_install:
 - travis_retry sudo apt-add-repository -y ppa:bitcoin/bitcoin
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc

 - travis_retry sudo apt-get update

# Install dependencies for Bitcoin and Tor
 - travis_retry sudo apt-get install -y build-essential libssl-dev libboost-all-dev libdb4.8-dev libdb4.8++-dev libgtk2.0-dev libevent-dev

# Installing bitcoind and bitcoin-cli from source
 - travis_retry wget https://bitcoin.org/bin/bitcoin-core-0.10.1/bitcoin-0.10.1.tar.gz
 - tar -xzf bitcoin-0.10.1.tar.gz && cd bitcoin-0.10.1 && ./configure --disable-tests --with-gui=no && make && sudo make install && cd ..
 - rm -rf bitcoin-0.10.1
 - which bitcoind
 - which bitcoin-cli 
 - bitcoind -regtest -rpcuser=user -rpcpassword=pass -daemon

# Install tor from source 
 - wget https://www.torproject.org/dist/tor-0.2.7.1-alpha.tar.gz
 - tar -xzf tor-0.2.7.1-alpha.tar.gz
 - cd tor-0.2.7.1-alpha/
 - ./configure --disable-unittests --disable-system-torrc
 - make -j4
 - sudo make install
 - cd ..

# Configure & launch tor service
 - echo "RunAsDaemon 1" >> ~/.torrc
 - echo "ControlPort 9051" >> ~/.torrc
 - echo "CookieAuthentication 1" >> ~/.torrc
 - echo "ExtORPortCookieAuthFileGroupReadable 1" >> ~/.torrc
 - tor 

# Wait until Tor control port is open
 - nc -zvv localhost 9051; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 9051..."; nc -zvv localhost 9051; out=$?; sleep 1; done
 
# Installing cabal and ghc
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
 - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - travis_retry cabal update
 
# Happy/alex hack for ghc > 7.8.1
 - |
   if [ $GHCVER = "head" ] || [ ${GHCVER%.*} = "7.8" ] || [ ${GHCVER%.*} = "7.10" ]; then
     travis_retry sudo apt-get install happy-1.19.4 alex-3.1.3
     export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH
   else
     travis_retry sudo apt-get install happy alex
   fi

 - travis_retry sudo apt-get -q -y install hlint || cabal install hlint
 - cabal install cabal-meta

# Generate some initial blocks
 - bitcoin-cli -regtest -rpcuser=user -rpcpassword=pass setgenerate true 101
 - bitcoin-cli -regtest -rpcuser=user -rpcpassword=pass getbalance

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal-meta install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls

script:
 - hlint bitgloom-btc/src --ignore="Parse error"
 - hlint bitgloom-driver/src --ignore="Parse error"
 - hlint bitgloom-www --ignore="Parse error" --ignore="Reduce duplication"

 - cabal-meta install --run-tests
