language: c
env:
 - CABALVER=1.22 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.1
 - CABALVER=1.22 GHCVER=head

matrix:
  allow_failures:
   - env: CABALVER=1.22 GHCVER=7.10.1
   - env: CABALVER=1.22 GHCVER=head
    
before_install:
 - travis_retry sudo apt-add-repository -y ppa:i2p-maintainers/i2p
 - travis_retry sudo apt-add-repository -y ppa:bitcoin/bitcoin
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc

 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install i2p
 - sudo sed -i /etc/default/i2p -e 's/RUN_DAEMON="false"/RUN_DAEMON="true"/'

# This generates the initial configuration
 - sudo service i2p start
 - sudo service i2p stop

# Open up the SAM and BOB bridges
 - sudo sed -i /var/lib/i2p/i2p-config/clients.config -e 's/clientApp.1.startOnLoad=false/clientApp.1.startOnLoad=true/'
 - sudo sed -i /var/lib/i2p/i2p-config/clients.config -e 's/clientApp.5.startOnLoad=false/clientApp.5.startOnLoad=true/'

 - sudo cat /var/lib/i2p/i2p-config/clients.config
 - sudo service i2p start

# Installing bitcoind and bitcoin-cli from source
 - travis_retry sudo apt-get install -y build-essential libssl-dev libboost-all-dev libdb4.8-dev libdb4.8++-dev libgtk2.0-dev

 - travis_retry wget https://bitcoin.org/bin/bitcoin-core-0.10.0/bitcoin-0.10.0.tar.gz
 - tar -xzf bitcoin-0.10.0.tar.gz && cd bitcoin-0.10.0 && ./configure --disable-tests --with-gui=no && make && sudo make install
 - rm -rf bitcoin-0.10.0
 - which bitcoind
 - which bitcoin-cli
 
 - bitcoind -regtest -rpc-user=user -rpc-password=pass -daemon
 - bitcoin-cli -regtest -rpc-user=user -rpc-password=pass setgenerate true 101
 - bitcoin-cli -regtest -rpc-user=user -rpc-password=pass getbalance
 
# Installing cabal and ghc
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
 - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - travis_retry cabal update
 
# Happy/alex hack for ghc > 7.8.1
 - |
   if [ $GHCVER = "head" ] || [ ${GHCVER%.*} = "7.8" ] || [ ${GHCVER%.*} = "7.10" ]; then
     travis_retry sudo apt-get install happy-1.19.4 alex-3.1.3
     export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH
   else
     travis_retry sudo apt-get install happy alex
   fi

 - cabal install hlint 
 - cabal install cabal-meta

# Wait until SAM and BOB bridges are open
 - nc -zvv localhost 7656; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 7656..."; nc -zvv localhost 7656; out=$?; sleep 1; done
 - nc -zvv localhost 2827; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 2827..."; nc -zvv localhost 2827; out=$?; sleep 1; done

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - cabal-meta install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls
# - travis_retry cabal install --only-dependencies --enable-tests --enable-benchmarks -j

script:
 - hlint bitgloom-btc/src --ignore="Parse error"
 - hlint bitgloom-i2p/src --ignore="Parse error"
 - hlint bitgloom-www/src --ignore="Parse error"

 - cabal-meta install --run-tests
